server:
    port: 8443
    servlet:
        contextPath: /publisher

multipart:
    maxFileSize: 10MB
    maxRequestSize: 1MB

spring:
    profiles:
        active: prod
        include: ldapgrp

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://mysql.internal.fr:3306/publisher?autoreconnect=true
        databaseName:
        serverName:
        username: publisher
        password: mypwd
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.esupportail.publisher.utils.MySQL5InnoDBCompressedDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.dialect: org.esupportail.publisher.utils.MySQL5InnoDBCompressedDialect

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: HTML
        cache: true

logging:
    config: "classpath:logback.xml"

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: publisher

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M

ldap:
    base: dc=esco-centre,dc=fr
    urls: ldap://ldap.internal.fr:389/
    userDn: cn=admin,ou=administrateurs,dc=univ,dc=fr
    password: mymdp
    timeLimit: 20000
    countLimit: 2000
    otherUserDisplayedAttributes: mail,ESCOUAI
    userGroupAttribute: isMemberOf
    otherUserOtherAttributes: isMemberOf, ENTPersonProfils, ESCOPersonProfils, ENTPersonJointure, ESCOUAICourant, ESCOSIRENCourant
    groupDNContainsDisplayName: true
    groupKeyMemberRegex: "cn=(.*),ou=groups,dc=esco-centre,dc=fr"
    groupKeyMemberIndex: 1
    userKeyMemberRegex: "uid=(.*),ou=people,dc=esco-centre,dc=fr"
    userKeyMemberIndex: 1
    groupDisplayNameRegex: ".*:([^:]*)"
    groupResolveUserMember: true
    groupResolveUserMemberByUserAttributes: true
     # for formatters
    escoGroupRegexp:
        properties:
            -
                groupMatcher: "((esco)|(cfa)|(clg37)|(agri)):admin:Publication_contenus:[^:]*"
                groupNameRegex: "[^:]*:([^:]*):([^:]*):[^:]*"
                groupNameIndex: "1,2"
                groupRecomposerSeparator: ":"
            -
                groupMatcher: "((esco)|(cfa)|(clg37)|(agri)):Etablissements:[^:]*_[0-9]{7}[a-zA-Z]:[^:]*:Profs Principaux"
                groupNameRegex: "[^:]*:Etablissements:[^:]*:([^:]*):(Profs Principaux)"
                groupNameIndex: "2,1"
                groupRecomposerSeparator: " - "
     # for designers  can be commented - used to attach groups that are not in the tree root or membrers on
    escoGroupDesigner:
        properties:
            -
                groupRootPattern: "((esco)|(cfa)|(clg37)|(agri)):Etablissements:[^:]*"
                groupAttachEndMatch: ":Profs"
                groupToAttachEndPattern: ":*:Profs_*,:*:Profs Principaux"
            -
                groupRootPattern: "ef2s:Etablissements:[^:]*"
                groupAttachEndMatch: ":Formateurs"
                groupToAttachEndPattern: ":*:Formateurs_*, :*:Responsable de formation"

cas:
    url:
        prefix: https://www.univ.fr/cas/
        login: https://www.univ.fr/cas/login
        logout: https://www.univ.fr/cas/logout

app:
    service:
        security: j_spring_cas_security_check
        redirectParamName: spring-security-redirect
        authorizedDomainNames: https://www.univ.fr,https://www.univ2.fr,https://www.univ3.fr
        protocol: https://
        idKeyProvider: esco_cas_publisher

        highlightClassification :
            name: "À la une"
            color: "#F44336"
            description: "Rubrique contenant les publications à mettre en avant"

        defaultTTL: 3600
        defaultTimeout: 15000

    admin:
        userName: admin
        groupName: "esco:admin:central"

    users:
        groupName: "((esco)|(cfa)|(clg37)|(agri)|(coll)):Applications:((Publisher)|(Publication_annonces)):.*"

    cors:
        allowed:
            origins: "*"

    upload:
        path: "/home/esco/uploads/"
        # 256Kb max
        imageMaxSize: 262144
        protectedPath: "/home/esco/privates/"
        filePathOfAuthorizedMimeTypes: "MimeTypes.txt"
        # 10MB max should be equals or lower than multipart.maxFileSize
        maxFileSize: 10485760

    authorizedServices:
        ipRange: "192.168.0.0/16"
