# security configuration (this key should be unique for your application, and kept secret)
#jhipster.security.rememberme.key: publisher

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    jpa:
        open-in-view: false
        properties:
            #hibernate.jdbc.time_zone: GMT+1
        hibernate:
            ddl-auto: none
    main:
        allow-bean-definition-overriding: true
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: publisher@localhost

    messageSource:
        cacheSeconds: 1
    thymeleaf:
        mode: HTML

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: ['configprops', 'health', 'env', 'threaddump', 'info', 'loggers']
  endpoint:
    health:
      show-details: when-authorized
      roles: 'ROLE_ADMIN'
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

logging:
    config: "classpath:logback.xml"

swagger:
    title: publisher API
    description: publisher applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
