package org.esupportail.publisher.domain;


import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@Entity
@Table(name = "T_READING_INDICATOR", uniqueConstraints = { @UniqueConstraint(columnNames = { "item_id" }) })
public class ReadingIndincator extends AbstractAutoGeneratedIdEntity implements Serializable {


    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
    @JoinColumn(name = "item_id")
    private AbstractItem item;

    private String user;

    @Column(name = "isRead")
    private boolean isRead;

    @Column(name = "readingCounter")
    private long readingCounter;

    public ReadingIndincator(AbstractItem item, String user, boolean isRead, long readingCounter) {
        super();
        this.item = item;
        this.user = user;
        this.isRead = isRead;
        this.readingCounter = readingCounter;
    }
}
