#!/bin/bash

# save the file as <git_directory>/.git/hooks/pre-commit.d/mvn_test and chmod +x

echo "Running mvn checks before commit"

# test Java version
java -version 2>&1 | grep -q -e "OpenJDK .*Temurin-11" && echo "Your java version is an OpenJDK Temurin version 11." || (echo "Your java version is not and OpenJDK Temuring version 11." && exit 1)

# retrieving current working directory
CWD=`pwd`
MAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# go to main project dir
cd $MAIN_DIR/../../
# running maven conform test
#MVN_RESULT=$(JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ ./mvnw notice:check sortpom:verify 2>&1)
MVN_RESULT=$(./mvnw notice:check sortpom:verify 2>&1)
if [ $? -ne 0 ]; then
  echo
  echo "${MVN_RESULT}"
  #echo "${MVN_RESULT}" | ((tee /dev/fd/5 | grep -A 10 -B 2 "Reactor Summary:" >/dev/fd/4) 5>&1 | sed -n -e '/^Failed tests:/,/Tests run:.*$/ p' ) 4>&1
  echo
  echo "Error while testing the code"
  # go back to current working dir
  cd $CWD
  exit 1
fi
# go back to current working dir
cd $CWD
